services:
  api:
    build: .
    container_name: capril-api
    command: fastapi run app --host 0.0.0.0 --port 80
    ports:
      - 8000:80
    networks:
      - capril-financas-network
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
networks:
  capril-financas-network:
    external: true